---
- name: SELinux無効化
  selinux: state=disabled
  become: yes
  tags: [os-setup]

- import_tasks: setup-redhat-6.yml
  become: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- import_tasks: setup-redhat-7.yml
  become: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: "ホスト名を {{ hostname }} に設定"
  hostname: name={{ hostname }}
  become: yes
  when: hostname is defined
  tags: [os-setup]

- name: パッケージを最新に更新
  yum: name=* state=latest exclude="kernel* centos*"
  become: yes
  tags: [os-setup]
