---
- name: "キーマップを {{ system.keymap }} に設定 "
  command: localectl set-keymap {{ system.keymap }}
  become: yes
  tags: [os-setup] 

- name: "ロケールを {{ system.lang }} に設定"
  command: localectl set-locale LANG={{ system.lang }}
  become: yes
  tags: [os-setup]

- name: "タイムゾーンを {{ system.timezone }} に設定"
  command: timedatectl set-timezone {{ system.timezone }}
  become: yes
  tags: [os-setup]
